name: SweetAutoResidence
version: '${version}'
main: top.mrxiaom.sweet.autores.SweetAutoResidence
api-version: 1.13
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
authors: [ MrXiaoM ]
commands:
  sweetautoresidence:
    description: 'The main command of SweetAutoResidence'
    aliases: [ sautoresidence, sautores, sares, sar ]
